id: IC27AC732
source: https://sakyaresearch.org
source_file: null
initial_creation_type: input
imported: '2022-06-18T20:05:13.495897'
last_modified: '2022-06-18T20:05:13.495910'
parser: null
source_metadata:
  title: Kālacakra commentary rGyud gsum snang ba (Old Phag gru lock print), colophon
    excerpt
  author: འགོས་ལོ་ཙཱ་བ་གཞོན་ནུ་དཔལ།
  description: 'Digital version 1.0 {Tibetan}, diplomatic edition of witness A; master
    xml (completed: 2020-07-23); revision in process, thematic TEI markup'
  file_info:
  - 'Language: Tibetan'
  - 'Coverage: Excerpt/Colophon'
  - 'Accessible: publicly'
  responibilities:
  - Digital edition:ས་སྐྱ་ཞིབ་འཇུག་ཁང་། (src)
  - Text input:བློ་བཟང་རྒྱལ་མཚན། (Dharamsala) (lg)
  - Editorial process:Mathias Fermer (mf)
  - TEI Encoding:ས་སྐྱ་ཞིབ་འཇུག་ཁང་།
  - TEI Markup:Mathias Fermer (mf)
  - Revisions/Corrections:བློ་བཟང་རྒྱལ་མཚན། (Dharamsala) (lg)
  text_witnesses: https://sakyaresearch.org/sources/4843
  bases:
    6b9c:
      title: Kālacakra commentary rGyud gsum snang ba (Old Phag gru lock print), colophon
        excerpt
      order: 1
      base_file: 6b9c.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
